name: Mend dep reacahbility Scan (unified CLI - Windows)

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    
    - name: build with pnpm
      run: p
npm install


    - name: Mend CLI Scan
      env:
        MEND_EMAIL: ${{secrets.MEND_SANDBOX_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_SANDBOX_USER_KEY}}
        MEND_URL: https://saas.mend.io
      run: |
        echo Mend email: $MEND_EMAIL
        echo Mend userkey: $MEND_USER_KEY
        echo Downloading Mend CLI
        curl https://downloads.mend.io/cli/windows_amd64/mend.exe -o mend.exe
        echo run Mend dependencies scan
        mend.exe dep -u -r -s "pnpm_tests//unified_CLI_reachability"
