name: Mend UA Scan (CLI)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    
    - name: build with pnpm
      run: pnpm install

    - name: Mend CLI Scan
      env:
        MEND_EMAIL: ${{secrets.MEND_DEMOCORP_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_DEMOCORP_USER_KEY}}
        MEND_URL: https://saas.mend.io
        WS_ENABLEIMPACTANALYSIS: TRUE
      run: |
        echo Mend email: $MEND_EMAIL
        echo Mend userkey: $MEND_USER_KEY
        echo Downloading Mend CLI
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        echo run Mend dependencies scan
        mend ua -product pnpm_tests -project nified_UA_reachability"
